### ISSUE TITLE
Fix iOS build problem

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#10]
building and linking the iOS lib seems to work, however, when running it after trying to login it freezes and we can see an error message on the console saying that it can't link to the `allocate` function.

**Comment by bitfriend** [comment]
Fixed by https://github.com/effektio/effektio/pull/163

**Comment by bitfriend** [comment]
`cocoapods` is using `ruby-macho` and `ruby-macho` occurs bug about 2.5GB+ library file.
The debug build of our library seems to be too large.
So we need to use release build.
We must use `cargo make --profile release ios`, not `cargo make ios`.
