### ISSUE TITLE
sign up error message doesn't disappear

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#108]
when signup / login fails, the error message stays for a few seconds, disappears and then immediately reappears... this happens quite a few times ... that is particularly confusing, when you try to resubmit.

![Screenshot_1653148587](https://user-images.githubusercontent.com/40496/169659658-67773024-f871-4b39-99eb-7abf7dd9a59e.png)

The error message should stay until the user clicks submit again, then it should disappear immediately.

**Comment by sachintha-s** [comment]
since this is a small thing, I fixed it with pull request #106

**Comment by sachintha-s** [comment]
fixed with #106
