### ISSUE TITLE
Align News Text on bottom and optional extend

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#116]
The text on news items should be aligned to the bottom and - if more than 2 lines - should be limited to 2 lines and extended upon tapping.

![Screenshot_1653423080](https://user-images.githubusercontent.com/40496/170123669-bee3e322-3df2-4665-9a91-f181a3e5dc97.png)

**Comment by gtalha07** [comment]
By expanding text you mean, the text should expand to above and not below right if its placed below. Otherwise it may cause overflow error?
