### ISSUE TITLE
Android version problem on flutter side

### ISSUE THREAD

**Issue by bitfriend** [effektio/effektio#122]
The following packages are not working on android API 23.
They are working on android API 30.
![image](https://user-images.githubusercontent.com/48786056/170834653-92736347-dfec-48a6-9c6d-09084cce4f99.png)
```
  html_editor_enhanced: ^2.4.0+1
  flutter_colorpicker: ^1.0.3
  emoji_picker_flutter: ^1.1.2
```
We can downgrade these packages, if we need android 23 later.

**Comment by gtalha07** [comment]
Patch via #175

**Comment by bitfriend** [comment]
We have another problem related to android api 23.
`dlopen` is not working and `Api.loadDynamic()` failed.

**Comment by bitfriend** [comment]
Fixed by https://github.com/effektio/effektio/pull/197
