### ISSUE TITLE
Show and handle Room Invites

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#127]
Description:
In Matrix/Effektio most people will be joining teams by being invited by others (UI still missing in Effektio). When that happens, sync will have another room in its list with the state `Invited`, that the user should either accept the invite for or decline. (As for now we ignore whether its an Effektio-Group or a chat you are invited to, but later will need to inform the user about that.)

What we need:

1. the rust SDK to expose the invited rooms (probably best to use a callback-system that hands over the room/ID for each room found to be invited to, and expose all relevant information)
2. the UI should show the invites on the top of the chat-messages-list, as well as on the top of the notifications area (as shown below) and allow the user to accept or decline. If the user accepts they will join and the room state will update.

To produce a testable scenario:
1. Create new room/DM with a different app (e.g. Element); invite the test account (`@test:effektio.org`); and 3. log into effektio with the test account. 

After the sync, the invite should appear and be possible for the user to interact with. 

Designs are still work in progress, but here is the current flow:
![image](https://user-images.githubusercontent.com/40496/171582188-36f4f464-9eae-46f4-9581-c11f4092084e.png)

**Comment by gtalha07** [comment]
General Implementation is completed.
