### ISSUE TITLE
libandroidicu.so for x86/armeabi-v7a/arm64-v8a

### ISSUE THREAD

**Issue by bitfriend** [effektio/effektio#128]
I used `path.join` to prepare file download path on flutter side.
This function depends on `libandroidicu.so` and I included this library into `jniLibs`.
Without this library, you can see this app crashes near this function.
I could get this library for only `x86_64`, not `x86`/`arm64-v8a`/`armeabi-v7a`.
I guess this library may have to be compiled on these 3 platforms.

**Comment by bitfriend** [comment]
If the usage of `libandroidicu.so` looks not nice, we can think another option.
In fact, `path.join` is not hard to implement by oneself.
Because it is just `concat` with `/`.
By the way what platforms are we planning?
Directory separator is different by platform.
For example, it is '\' on windows, but '/' on linux, android, ios.

**Comment by gnunicorn** [comment]
Let's only use `path`-stuff from within the rust-side. It brings all we need and we don't need any additional dependencies.

**Comment by bitfriend** [comment]
Understood.
It was fixed in issue77.
