### ISSUE TITLE
Incoming text messages not showing in real-time

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#130]
Chat should update messages in real-time in a room.

**Comment by bitfriend** [comment]
I guess it would be fixed when #77 and #127 are merged.

**Comment by gtalha07** [comment]
I have already fixed it in #129  branch although I have not pushed the code yet. Just to keep atomic fixes. Need approval for #129 and merge so I can open PR for it.

**Comment by gtalha07** [comment]
The fix is linked with getX depedency so this needs to get merged before I push #130 fix

**Comment by bitfriend** [comment]
Yes, because #77 is support for image/file message.

**Comment by gtalha07** [comment]
Fixed via #142

**Comment by gtalha07** [comment]
Closing as per #217
