### ISSUE TITLE
Support markup in ChatList page

### ISSUE THREAD

**Issue by bitfriend** [effektio/effektio#134]
`ChatScreen` is main text editing page so it supports markup.
But now `ChatList` page doesn't support markup.
![image](https://user-images.githubusercontent.com/48786056/172851211-291845c8-ec0d-41bd-b6bc-36fbcce27e83.png)

**Comment by gtalha07** [comment]
We could probably use this: https://pub.dev/packages/markup_text

**Comment by bitfriend** [comment]
Great

**Comment by gtalha07** [comment]
Closing per #191
