### ISSUE TITLE
Emoji-Reactions

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#139]
We want to react on messages in chat via an Emoji. The matrix network protocol already has a message system for that in place. Designs also exist already:

![grafik](https://user-images.githubusercontent.com/40496/173411165-1195d4ec-5e13-47e5-be25-e7f1d146630d.png)

![grafik](https://user-images.githubusercontent.com/40496/173411371-2d19038d-e42e-45f5-a2fa-608e66fbc658.png)

We need to:

1. implement the sdk core for tracking emojis per message
2. core function to send emojis
3. inform the UI about emoji updates
4. implement the UI for emoji sending and display

**Comment by gtalha07** [comment]
API references: https://pub.dev/documentation/flutter_chat_ui/latest/flutter_chat_ui/Chat/customMessageBuilder.html
https://pub.dev/documentation/flutter_chat_ui/latest/flutter_chat_ui/Chat/bubbleBuilder.html

**Comment by gtalha07** [comment]
Closing as per #411.
