### ISSUE TITLE
Custom Bottom Chat Input Message Widget

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#144]
Need to implement customized input message widget in chat as according to design.
![Group 1364](https://user-images.githubusercontent.com/68579938/174478489-93f645d6-250b-49fa-a289-f0934acaeeea.png)

**Comment by gtalha07** [comment]
To implement this with package we're using, you'll define a seperate widget for this and call that widget within
```
(new) Chat Chat({
  Widget? customBottomWidget,
 )
```
```
{Widget? customBottomWidget}
Type: Widget?
Allows you to replace the default Input widget.

```

**Comment by sachintha-s** [comment]
Thanks, 
@gtalha07  Do we have any design related to emojis or should we use an emoji picker package to implement the emoji picking part?

**Comment by gtalha07** [comment]
Closing via #176.
