### ISSUE TITLE
Fetch user avatars images from rust.

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#207]
We would need to fetch user avatars from backend to render on flutter chat ui via the ```RoomMessage``` API.

**Comment by bitfriend** [comment]
Yeah, API was already implemented.
`room.getMemeber(userId).avatar()`

**Comment by bitfriend** [comment]
Fixed by https://github.com/effektio/effektio/pull/211

**Comment by bitfriend** [comment]
I changed `room.getMember(UserId userId)` to `room.getMember(String userId)`, because flutter can't access `UserId` object from rust and it is simple for flutter to deal with `String`.
