### ISSUE TITLE
Mention ```@``` and highlight message support in chat.

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#212]
Chat should have the support of mentioning someone via ```@``` and highlighting the message. A regex pattern would be required and suitable for it. 

Note: Please refer to [effektio docs](https://docs.effektio.org/api/main/dart-sdk/effektio/Client-class.html) for relevant APIs and file an issue if needs implementing or missing.

**Comment by sachintha-s** [comment]
fixed #277
