### ISSUE TITLE
Refactor RoomTimeline fire event with returning stream.

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#232]
We have a RoomTimeline class in rust with method ```next()```. This method is returning RoomMessage with future value. However for p2p conversation, the method should be returning stream to emit multiple events instead of single event. The following is a workaround to make it stream with peroidic callings to future but this approach could get app intensive.
```
 Stream<RoomMessage> newRoomMessage() =>
        Stream.periodic(const Duration(milliseconds: 800))
            .asyncMap((_) => _stream!.next());
    newRoomMessage().listen((event) {
      if (event.sender() != user.id) {
        _loadMessage(event, messages);
        update(['Chat']);
      } else {
        update(['Chat']);
      }
    });
``` 
**Requirement:**
We should refactor ```next()``` to be event stream so it can listen to stream and yield multiple events.

**Comment by bitfriend** [comment]
Fixed by https://github.com/effektio/effektio/pull/256
