### ISSUE TITLE
Apply CachedNetworkImage to Image Message

### ISSUE THREAD

**Issue by bitfriend** [effektio/effektio#255]
@gtalha07 introduced `CachedNetworkImage` for user avatar.
Will it be necessary to apply `CachedNetworkImage` to image message too?

**Comment by gtalha07** [comment]
Actually the PR applies fixes to image messages which doesn't render  when scrolling through images. ```CachedMemoryImage``` allows it to cache. ```CachedNetworkImage``` can be used if image source is remote URL, the case which is also handled.

**Comment by bitfriend** [comment]
Okay, will check soon.

**Comment by bitfriend** [comment]
This is fixed and merged as per [PR#250](https://github.com/effektio/effektio/pull/250)
