### ISSUE TITLE
implement basic chat 

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#3]
with https://pub.dev/packages/flutter_chat_ui

**Comment by gtalha07** [comment]
Tasks:

- [ ] Display Chat List with room avatars and latest message 
- [ ] Implement Chat Room with timeline
- [ ] Implement attachment functionalities (File and Image)
- [ ] Seen tick indicators
- [ ] Link preview in conversation
- [ ] Group/Member Info
