### ISSUE TITLE
Replies

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#302]
We want to be able to reply to messages directly - probably in a similar way as telegram, whatsapp and alike do it:

 1. swipe on message
 2. visually attaches the message in the posting text box with a "replying to"
 3. notice the event this is a reply-to
 4. render the replying-to message in the message stream

**Comment by kokodavid** [comment]
https://user-images.githubusercontent.com/47295684/203241671-19b8c6ed-a6b2-430a-abc0-3ed01def26ba.mp4

**Comment by gtalha07** [comment]
Closing as per #395 merged.
