### ISSUE TITLE
Requests and Invites APIs

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#312]
Groups aka Rooms should be able to invite users via their domains .i.e. (matrix.org, effektio.org).  
![image](https://user-images.githubusercontent.com/68579938/198035757-a45945b8-681f-4dba-918b-8c9e53e25fbb.png)
![image](https://user-images.githubusercontent.com/68579938/198035835-efa5d487-d7c4-440f-893d-8087acddeb97.png)

**Comment by bitfriend** [comment]
Do you want to fetch users out of current room?

**Comment by bitfriend** [comment]
@gtalha07: As we can see, user can enter other's address into invitation address bar.
And @gnunicorn recommended suggestion list can be compiled via aggregation of user's all DMs.
The former is for unknown user and the latter is for known user.
I will implement it.

**Comment by bitfriend** [comment]
Solved by https://github.com/effektio/effektio/pull/339
