### ISSUE TITLE
Verification for Encryption support

### ISSUE THREAD

**Issue by bitfriend** [effektio/effektio#327]
The incoming message is updated in chat list for unencrypted room.
But not for encrypted room.

https://user-images.githubusercontent.com/48786056/199714214-f58ef286-8980-41a8-a903-f632ae157140.mp4

BTW element app is seeing everything in even encrypted room.
Of course, our app has no UI that user can input the security key.
If user inputs it, our app can decrypt the encrypted room message.

Windows desktop cannot verify.
As I said before, that device is in list that doesn't support encryption.
![image](https://user-images.githubusercontent.com/48786056/199714414-85adf0d7-b76d-4fed-94e2-5a4a87e54647.png)
Literally, windows desktop doesn't support encryption, so it can't decrypt the encrypted room message.

Android seems to not support encryption like windows desktop.
![image](https://user-images.githubusercontent.com/48786056/199714531-690e05c2-9260-44e5-9e9a-046e155d96ba.png)
Weird, app was working well before.

Now `main` branch can reproduce this bug.

**Comment by bitfriend** [comment]
I think security key should be inputted before we can decrypt the encrypted room message.
Element website has the following UI for new login.
![image](https://user-images.githubusercontent.com/48786056/199722758-d8f38000-9e4d-43f9-84e5-4fabc5cdc658.png)
Next screen
![image](https://user-images.githubusercontent.com/48786056/199722873-7b54ad85-af00-4d5f-be14-d4012ec18365.png)
Now our app has no such UI and logic.

**Comment by bitfriend** [comment]
At that time, element website supports encryption and is in unverified status.
![image](https://user-images.githubusercontent.com/48786056/199723896-8dcbb806-2c7f-4bb3-b79e-a5753049ac5e.png)

**Comment by bitfriend** [comment]
I sent markdown message on my effektio desktop and I read it on test element web and my element desktop.
![image](https://user-images.githubusercontent.com/48786056/199755604-9cf156d3-3a3f-46ce-a587-4d66e69e1d0c.png)
1st screen is my account in effektio desktop.
2nd screen is test account in element website.
3rd screen is my account in element desktop.

As you see, sending from our app is successful and element web & desktop received that message.
BTW there is a small difference in display between accounts.
2nd screen has no shield near message.
But 3rd screen has a shield near message.
2nd screen is of test account and 1st/3rd screens are of my account.

**Comment by bitfriend** [comment]
Latest message from this channel shows log `One time key already exists`.
I don't know what it means.
![image](https://user-images.githubusercontent.com/48786056/199970759-a4760dea-ee6b-423d-92a7-ea37fb82a88f.png)
This issue seems to be not session storage of windows, because this issue occurred in android too.

**Comment by gnunicorn** [comment]
weird. my latest android sessions shows up as:

![grafik](https://user-images.githubusercontent.com/40496/200527544-68fe2eed-59a9-4c8c-a2bb-ce81aee4c24d.png)

---

we should probably give the devices some names, too. The random string isn't that helpful all by itself...

**Comment by bitfriend** [comment]
Desktop doesn't show `Verify` button, because it doesn't support encryption and it cannot decrypt message.
Mobile shows `Verify` button, because it supports encryption and it can decrypt message.
This is primary issue that we have to solve.

**Comment by bitfriend** [comment]
After upgrade to `matrix-sdk v0.6`, this error disappeared.
I guess it was issue from version of matrix server.
