### ISSUE TITLE
Re-login failed after logging out of client.

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#333]
Cannot login again after logging out of the client. According to findings of @bitfriend, IO exception is occuring while authentication. The issue is specific to desktop platforms (macOS/Windows), not tested on linux build yet.
![image](https://user-images.githubusercontent.com/68579938/199950183-02aebadc-08dc-4ede-ba98-87e782a3679b.png)

**Comment by bitfriend** [comment]
This issue seems to be from anti-virus.
When it is disabled, login is working well even multiple times.

**Comment by bitfriend** [comment]
After upgrading of `matrix-sdk` to v0.6, this issue seems to be fixed.
Now `main` is not showing this issue.

**Comment by gtalha07** [comment]
confirmed and closing as fixed per #300.
