### ISSUE TITLE
Sometimes flutter doesn't accept some keyboard input on desktop app

### ISSUE THREAD

**Issue by bitfriend** [effektio/effektio#334]
Sometimes flutter doesn't accept some keyboard input like backspace or arrow key on windows/macos desktop app.

**Comment by bitfriend** [comment]
This code looks like bug.
https://github.com/effektio/effektio/blob/f7e8af8dab0b895d5aff4207eb96f29926ecd6fe/app/lib/widgets/CustomChatInput.dart#L118-L121
If network is not good, `typingNotice()` will be delayed and `onChanged()` event will not be completed soon.

**Comment by gtalha07** [comment]
Relates to known issue: https://github.com/flyerhq/flutter_chat_ui/issues/338

**Comment by gnunicorn** [comment]
we should run typingNotice in fire and forget manner. Let's not wait for it. No reason to.
