### ISSUE TITLE
internet connectivity state in app

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#337]
We should add network aware handlers/widgets in the application which would inform the internet connectivity state of the application. These packages seems to be helpful:
https://pub.dev/packages/connectivity_plus
https://pub.dev/packages/connectivity_wrapper

**Comment by kokodavid** [comment]
![image](https://user-images.githubusercontent.com/47295684/210715399-aba880eb-586c-4e32-a932-8b1e90923126.png)

**Comment by gtalha07** [comment]
Closed as #432 merged.
