### ISSUE TITLE
[Chat] Widget library exception on scrolling room messages area.

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#342]
![image](https://user-images.githubusercontent.com/68579938/200558419-828a3ec4-1cc3-4303-9c2a-d73b8af4ddbc.png)

**Comment by gtalha07** [comment]
The issue seems to be occuring directly in the package itself.
https://github.com/flyerhq/flutter_chat_ui/issues/349

**Comment by gtalha07** [comment]
Upon digging, the issue arises because of fetching duplicate messages from outdated pagination API (from v0.5 matrix sdk), which triggers exception at package internal list. Pagination API needs to get updated in accordance with v0.6 specification.

**Comment by bitfriend** [comment]
On v0.5, pagination was performed by periodic API calling.
But on v0.6, pagination is performed by timeline stream.
When event decryption failed in encrypted room, it will be excluded from message rendering.
Event decryption error will be dealt as another issue.
