### ISSUE TITLE
Some room messages appear with wrong ordering.

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#409]
There is some bug related with events not appearing correct in order according to their timestamps.
![image](https://user-images.githubusercontent.com/68579938/208923312-40758528-1548-4ada-8874-f80741bc89d5.png)

**Comment by bitfriend** [comment]
Talha, now element app is offline on your side too?

**Comment by gtalha07** [comment]
> Talha, now element app is offline on your side too?

Yeah, don't know the reason.
