### ISSUE TITLE
Cannot find "X" in this scope

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#42]
These issues are coming from the latest commits and can be reproducable by running "cargo make build android". Log file is attached
[logs.txt](https://github.com/effektio/effektio/files/8314593/logs.txt)

**Comment by gnunicorn** [comment]
To build for android, you can limit the call to `cargo make android` (the `build` isn't necessary here). 

It looks like the `build` triggers a `cargo build --all --all-features`, which _isn't_ actually supported (we had to hack a thing to get cbindgen support going, but activating the `cbindgen`-feature will not be build actually). I'll take a look at it.

**Comment by gnunicorn** [comment]
I have a patch upcoming.
