### ISSUE TITLE
Chat list sorting

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#438]
We should sort the list of chats in a "latest updated first" fashion. Right now the order seems kinda random and it makes it hard to find the right chat.

**Comment by gtalha07** [comment]
> We should sort the list of chats in a "latest updated first" fashion. Right now the order seems kinda random and it makes it hard to find the right chat.

This seems to be working partially, that is in "real-time" message incoming event, sorts it to the top. Work is to be done on initial fetch by sorting based on ```RoomMessage``` timestamp.
