### ISSUE TITLE
Build fail on some emulators.

### ISSUE THREAD

**Issue by sachintha-s** [effektio/effektio#68]
Build fail on emulators like **Pixel 3a API 28 x86, Pixel 3a API 30 x86,** but works on the emulator with **Pixel 4 API 32 x86_64**

It displayed the following message and finally lost connection to the device.
![Screenshot 2022-04-24 165438](https://user-images.githubusercontent.com/65540448/165856878-579983b3-040d-4cc4-af2d-b29bca77d32e.png)

This is the full terminal message.
[terminal message.txt](https://github.com/effektio/effektio/files/8586991/terminal.message.txt)

**Comment by bitfriend** [comment]
It seems to be issue on rust side.
Anyway it is working well.
