### ISSUE TITLE
Text-Input box too large

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#82]
see at the bottom: the input box is three times as large as the actual text. This needs to be trimmed down and made a bit cleaner.

![Screenshot_1651678725](https://user-images.githubusercontent.com/40496/166718283-c9ae9207-6211-4906-9ce3-c98dda91b401.png)

**Comment by gtalha07** [comment]
**Does this look better or it needs more trimming?**
![Screenshot_20220505_183611_org effektio app](https://user-images.githubusercontent.com/68579938/166935294-203f446f-e3c3-44de-a6a7-a2dda5734153.jpg)

**Comment by gnunicorn** [comment]
@gtalha07 very nice. thanks.
