### ISSUE TITLE
FormatException (FormatException: Missing extension byte (at offset 1))

### ISSUE THREAD

**Issue by inderjeet-developer7** [effektio/effektio#99]
19
W/org.effektio( 7920): matrix_sdk::encryption: Error when sending out an outgoing E2EE requesterror=Http(Api(Server(Known(ClientApi(Error { kind: Unknown, message: "One time key signed_curve25519:AAAAAAAAAA0 already exists. Old key: {\"key\":\"ea055knPrE3Jua5An2rfIyqIxRLNKmK7ik56Efri3nY\",\"signatures\":{\"@141:effektio.org\":{\"ed25519:guest_device\":\"3cc+i/HGp8wUq1liBhTskU9tuNAtBnjx/8bG3tR4ShbfyW2J5geaYSQtyq5A0qffFsfScFunaVyBYn9crnjYAQ\"}}}; new key: {'key': 'KXjYWThQumSY9jnOJ6DTXTJaxyUBbLgimz5xd9IwvV4', 'signatures': {'@141:effektio.org': {'ed25519:guest_device': 'y1+09JUnS6d54nM5JKENjhris/T25nbWyvuHoQXyy5neUD7jdaIuqIxmVSXaQLGhAl9Wq/uW7j12S0BaXznDAQ'}}}", status_code: 400 }))))
)

![Screenshot (31)](https://user-images.githubusercontent.com/65702289/168416868-62dc86d7-5cf6-4f44-bbf4-24729763d63b.png)

**Comment by gtalha07** [comment]
PR #96 have already fixed it and is now live in main branch. Please check again if you have pulled out latest code.
